name: release

on:
  push:
    branches:
      - main

env:
  IMAGE_REGISTRY: ghcr.io
  IMAGE_REPO: ${{ github.repository_owner }}/golden-container
  IMAGE_TAGS: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      # Needed for signing the container image with GitHub OIDC Token
      id-token: write
      # Needed to push to ghcr.io registry
      packages: write

    outputs:
      image:  ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_REPO }}
      digest: ${{ steps.push-image.outputs.digest }}

    steps:
    - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

    - name: Install Cosign
      uses: sigstore/cosign-installer@cad07c2e89fa2edd6e2d7bab4c1aa38e53f76003 # v4.1.1

    - name: Install Syft
      uses: anchore/sbom-action/download-syft@e22c389904149dbc22b58101806040fa8d37a610 # v0.24.0

    - name: Log in to ghcr
      uses: redhat-actions/podman-login@4934294ad0449894bcd1e9f191899d7292469603 # v1
      with:
        registry: ${{ env.IMAGE_REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Buildah Action
      id: build-image
      uses: redhat-actions/buildah-build@9dc2ade9b5db229966b5025ae266311e12f349c4 # v2
      with:
        image: ${{ env.IMAGE_REPO }}
        tags: ${{ env.IMAGE_TAGS }}
        dockerfiles: ./Containerfile

    - name: Push to ghcr
      id: push-image
      uses: redhat-actions/push-to-registry@5860fc963bf8f2b3221773a023141612f010c469 # v2
      with:
        registry: ${{ env.IMAGE_REGISTRY }}
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}

    - name: Sign image with GitHub OIDC Token
      run: cosign sign --yes ${IMAGE_REGISTRY}/${IMAGE_REPO}@${DIGEST}
      env:
        DIGEST: ${{ steps.push-image.outputs.digest }}

    - name: Generate and store SBOM
      run: |
          syft "${IMAGE_REGISTRY}/${IMAGE_REPO}@${DIGEST}" -o spdx-json=sbom-spdx.json
          cosign attest --yes --predicate sbom-spdx.json --type spdx "${IMAGE_REGISTRY}/${IMAGE_REPO}@${DIGEST}"
      env:
        DIGEST: ${{ steps.push-image.outputs.digest }}

  provenance:
    needs: [build]
    permissions:
      actions: read # for detecting the Github Actions environment.
      id-token: write # for creating OIDC tokens for signing.
      packages: write # for uploading attestations.
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_container_slsa3.yml@f7dd8c54c2067bafc12ca7a55595d5ee9b75204a # v2.1.0 
    with:
      image: ${{ needs.build.outputs.image }}
      digest: ${{ needs.build.outputs.digest }}
      registry-username: ${{ github.actor }}
    secrets:
      registry-password: ${{ secrets.GITHUB_TOKEN }}

  validate:
    needs: [provenance, build]
    runs-on: ubuntu-latest
    steps:
      - name: Validate image
        uses: conforma/action-validate-image@af7a6e9cb64a47f35e64268fcdee06803a0a655c # v1.0.419
        with:
          image: ${{ needs.build.outputs.image }}@${{ needs.build.outputs.digest }}
          identity: https:\/\/github\.com\/(slsa-framework\/slsa-github-generator|${{ github.repository_owner }}\/${{ github.event.repository.name }})\/
          issuer: https://token.actions.githubusercontent.com
    
  promote:
    runs-on: ubuntu-latest
    needs: [validate, build]
    steps:  
      - name: Push latest-validated image tag 
        run: |
          skopeo copy \
          --dest-creds=${{ github.actor }}:${{ github.token }} \
          docker://${{ needs.build.outputs.image }}@${{ needs.build.outputs.digest }} \
          docker://${{ needs.build.outputs.image }}:latest
  